import { GetServerSidePropsResult, NextPage } from 'next';
import Head from 'next/head';
import { PostContentDTO, PostCtx } from '../../interfaces/post';
import { postsRepo } from '../../core/PostRepo';

export interface PostPageProps {
  post: PostContentDTO;
}

export const getServerSideProps = async ({ params }: PostCtx): Promise<GetServerSidePropsResult<PostPageProps>> => {
  const { id } = params;

  await postsRepo.connect();

  const post = await postsRepo.getOne(id);

  if (!post) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      post,
    },
  };
};

const Post: NextPage<PostPageProps> = ({ post }) => {
  return (
    <>
      <Head>
        <title>Blog post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <h1>{post.title}</h1>
        <div dangerouslySetInnerHTML={{ __html: post.content }} />
      </article>
    </>
  );
};

export default Post;
