import { GetServerSidePropsResult, NextPage } from 'next';
import Head from 'next/head';
import { stubGetPost } from '../../stub/stubs';
import { PostContent, PostCtx } from '../../interfaces/post';

export interface PostPageProps {
  post: PostContent;
}

export const getServerSideProps = async ({ params }: PostCtx): Promise<GetServerSidePropsResult<PostPageProps>> => {
  const { id } = params;

  const post = await stubGetPost(id);

  if (!post) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      post,
    },
  };
};

const Post: NextPage<PostPageProps> = ({ post }) => {
  return (
    <>
      <Head>
        <title>Blog post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <h1>{post.title}</h1>
      </article>
    </>
  );
};

export default Post;
