import React from 'react';
import { GetServerSideProps, GetServerSidePropsResult, NextPage } from 'next';
import Head from 'next/head';
import { PageSection } from '../../components/layout/shared';
import { queryInitialApolloState } from '../../core/graphql-client';
import { GET_CERTAIN_POST } from '../../core/graphql-client';
import { PostLoader } from '../../components/postPage/PostLoader';
import { ParsedUrlQuery } from 'querystring';
import { FullPostDTO } from '../../contracts/PostDTO';

interface PostPageProps {}

interface FullPostData {
  post: FullPostDTO;
}
interface FullPostQueryVars {
  slug: string | string[] | undefined;
}

interface PostCtx extends GetServerSideProps<ParsedUrlQuery> {
  params: PostParams;
}

interface PostParams extends ParsedUrlQuery {
  id: FullPostDTO['id'];
}

export const getServerSideProps = async ({ params }: PostCtx): Promise<GetServerSidePropsResult<PostPageProps>> => {
  const { slug } = params;

  const { data, initialApolloState } = await queryInitialApolloState<FullPostData, FullPostQueryVars>({
    query: GET_CERTAIN_POST,
    variables: { slug },
  });

  if (!data.post) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      initialApolloState,
    },
  };
};

const Post: NextPage<PostPageProps> = () => {
  return (
    <>
      <Head>
        <title>Blog post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageSection>
        <PostLoader />
      </PageSection>
    </>
  );
};

export default Post;
