import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import { stubGetPostsList } from '../stub/stubs';
import { Post } from '../interfaces/post';

export const getServerSideProps: GetServerSideProps = async () => {
  const posts = await stubGetPostsList();

  return {
    props: {
      posts,
    },
  };
};

const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {posts.map((post: Post) => (
        <li key={post.id}>
          <Link key={post.id} href={`/post/${post.id}`}>
            <a>{post.title}</a>
          </Link>
        </li>
      ))}
    </>
  );
};

export default Home;
