import React from 'react';
import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';
import { PageSection } from '../components/layout/shared';
import { PostsWrapper } from '../components/indexPage/PostsWrapper';
import { postsRepo } from '../core/db';
import { initializeApollo } from '../core/apollo/client/client';
import { GET_ALL_POSTS } from '../core/apollo/client';

export const getServerSideProps: GetServerSideProps = async () => {
  const { posts, lastId, hasMore } = await postsRepo.getAll();

  const apolloClient = initializeApollo();

  apolloClient.cache.writeQuery({
    query: GET_ALL_POSTS,
    data: {
      getPosts: {
        lastId,
        posts,
        hasMore,
      },
    },
  });

  return {
    props: {
      initialApolloState: apolloClient.cache.extract(),
    },
  };
};

const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageSection>
        <PostsWrapper />
      </PageSection>
    </>
  );
};

export default Home;
